version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      day: 'sunday'
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      day: 'sunday'
      interval: 'weekly'
    groups:
      npm-security:
        applies-to: security-updates
        patterns: ['*']
      npm-update:
        applies-to: version-updates
        patterns: ['*']
